### ISSUE TITLE
Research into generator for smart contract

### ISSUE THREAD

**Issue by au-shah** [Charlotte8699/Private-Data#10]
- [ ] How can we add the verify function into this generator?

- [x] What will be different? What will the flow be like?

- [x] Will we have two separate generators perhaps? One for non-pd and one with pd?

**Comment by Lynn14m** [comment]
Decided to have **two separate generators** - one for generating a smart contract project without private data (the one available currently), and another for generating a smart contract project with private data. Having one generator would mean adding complexity to the smart contract that's potentially not needed if user has no intention at all to use private data, so having separate generators would work better!

**Comment by Lynn14m** [comment]
Keeping the CRUD operations and the assetExits and adding verify function.
