### ISSUE TITLE
Sample smart contract with verify

### ISSUE THREAD

**Issue by au-shah** [Charlotte8699/Private-Data#16]
Should create a sample smart contract with verify transaction so @Lynn14m can use this to create her generator.

- [x] createAsset 

- [x] readAsset

- [x] assetExists

- [x] verifyAsset

- [x] deleteAsset

**Comment by erin-hughes** [comment]
A few wee comments on the smart contract:

1. On line 101 we need a better check for if the org submitting the transaction is able to verify (I know we already spoke about this but I didn't want to leave it out)
2. To differentiate between the regular smart contracts and the private data one, the default asset name should probably be MyPrivateAsset or something
3. And the collection name should probably just be myCollection
4. You may want to rephrase some of your error messages: `Transient data not supplied. Try again.` on line 74 is a bit aggressive

**Comment by au-shah** [comment]
Made relevant changes for all of the above suggestions. Except the first one, as this can only be done once we have set up our Ansible network and are sure of the MSPId for the organisation that will own the PDCollection.
