### ISSUE TITLE
Final Scenario write-up

### ISSUE THREAD

**Issue by au-shah** [Charlotte8699/Private-Data#2]
Should show our final scenario here, whether it be in text or in a visual diagram (preferred so its easier to explain/understand)

**Comment by Charlotte8699** [comment]
So far...

<img width="1162" alt="Screenshot 2019-11-13 at 16 25 57" src="https://user-images.githubusercontent.com/52786879/68945497-71996580-07a8-11ea-9afd-af6f635b6328.png">

This will likely change over the course of the project as our scenario becomes more refined
